### PR TITLE
Add custom template option

### PR DESCRIPTION
**Pull request by jmblog**
Hi, I wanted to specify my own template file for the HTML output. So I added the option for it.

### CODE REVIEW

**Comment by 1000ch** [comment]
:100:

**Comment by 1000ch** [comment]
Specifying template file may be divided from format option.
What do you think of this idea? @jmblog @t32k

**Comment by t32k** [comment]
Thank you so much @jmblog!!
I love this feature, so I'd like many people to use it.
The feature enable us to make various formats not only HTML, such as Markdown, CSV and so on.
That's why I agree with #104 idea.

**Comment by jmblog** [comment]
@t32k @1000ch Yeah, I totally agree with #104 idea. Actually I'm trying to rename the generated HTML file to markdown in my project. Thank you for your proposal.

**Comment by t32k** [comment]
We're going to release this feature at v5.0.0.  We've already taken in it #105, so I'm closing this pull request. Thanks for your help!

**Pull request closed without merging**
